name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1

    - name: Setup Dotnet SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402'
        
    - name: Configure Dotnet SDK for one-time use    
      run: set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    
    - name: Generate Build Number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}}        
    
    - name: Build Nuget Package
      run: dotnet pack -c Release --version-suffix ci-${{BUILD_NUMBER}} --output '../../nupkgs' HangfireExtension.sln
    
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Configure Github Package Registry for Nuget.exe
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/Roganik/index.json" -UserName Roganik -Password ${{secrets.github_token}}    
  
    - name: Nuget Push
      run: nuget push nupkgs/*.nupkg -Source "GitHub" 
